include=/home/pug/.cache/wal/colors-fuzzel.ini

[main]
font = Iosevka Nerd Font:size=12
dpi-aware=yes
icon-theme=Papirus-Dark
fields=filename,name,generic
terminal=kitty
layer=overlay
lines=15
width=40
horizontal-pad=20
vertical-pad=10
inner-pad=10

[border]
width=2
radius=12

[dmenu]
exit-immediately-if-empty=yes

# Include pywal colors

[colors]
background=0d0d1fb0
[colors]
prompt=c2c2c7ff
text=c2c2c7ff
placeholder=c2c2c7ff
input=c2c2c7ff
match=c2c2c7ff
selection=39476Aff
selection-text=0d0d1fff
selection-match=c2c2c7ff
border=39476Aff
